RIKI-05/MOMOMIA

MOMOMIA/index.html

Fixed Navbar #11 
Styled and added fixed navbar, now its easy to navigate

Added fixed navbar

---

MOMOMIA/About us/About.css
MOMOMIA/About us/About.html
MOMOMIA/index.html

Added About us Section in the Website

Add About us Section

---

MOMOMIA/styles.css

Hey 👋 @RIKI-05 ,
I have made the navbar height smaller and logo smaller to make it nice both in desktop and mobile version
Issue: #19 
Please review my PR and let me know if any changes to be made
Please add `hacktoberfest-accepted` label so that I can keep track of my contributions this month
Screenshot:
Appreciate that

Updated navbar and logo

---

MOMOMIA/styles.css

Color of footer clickables changed to #ffc107

Updated styles.css

---

MOMOMIA/styles.css

Added Advanced CSS on order now button , which animate on Hover and clicking .
Resolved issue #5

Updated Animation on "order now" . issue #5

---

MOMOMIA/index.html

Revert "Improved look of Headings "

---

MOMOMIA/styles.css

*changed logo size.
*social icons hover color to desired color.
*social icons responsiveness improved for small screens.

Logo Size, social icons hover

---

MOMOMIA/index.html

Font sized changed

---

MOMOMIA/index.html

Inverted the colours of navbar as you said the text to be black and navbar to white
Fixed issue #40

Inverted the colours of navbar

---

MOMOMIA/index.html
MOMOMIA/styles.css

Added Linkedin icon & link to the Linkedin page in the footer section. Fixed the hover effect on footer icons.
Fixed issue #45

Updated icon links & fixed hover effect

---

MOMOMIA/index.html

[fix] issue #52

---

MOMOMIA/styles.css

Added the glow effect to the checkout button

---

MOMOMIA/styles.css

Added zoom on hover effect on momo platter
fixed issue #72

Added zoom hover effect on homeImg

---

MOMOMIA/index.html
MOMOMIA/styles.css

Added Black color to scroll bar

---

MOMOMIA/index.html
MOMOMIA/terms_of_service.css
MOMOMIA/terms_of_service.html

solved issue no #62

---

MOMOMIA/terms_of_service.css

Changed the color theme of Terms of Service page font: white page: black

---

MOMOMIA/index.html

Description:
Extra food and beverages items added to make the card equal
Isse: #60 
Screenshot:
@RIKI-05 Please add `hacktoberfest-accepted` label to track of my contributions

Extra items added

---

MOMOMIA/index.html
MOMOMIA/styles.css

Footer update with all requirements.

footerupdate 

---

MOMOMIA/index.html

Description:
Footer logo font changed to Robot and font size made standard to nav's logo
Issue: #65 
Screenshot:

footer logo font changed

---

MOMOMIA/styles.css

Revert "Update styles.css"

---

MOMOMIA/index.html

footer improved

---

MOMOMIA/index.html
MOMOMIA/styles.css

Fixes #99
https://user-images.githubusercontent.com/90052358/194915277-07e31cfa-c3d4-434a-93c1-cd6863ff58f3.mp4

Improve Responsiveness

---

MOMOMIA/index.html

Thank you for reading my pull request.
**### Screenshot:**
**- Navbar**
**- Footer**

Changed fonts of Monomia in navbar and footer.

---

MOMOMIA/index.html
MOMOMIA/styles.css

Hygiene section improvement

---

MOMOMIA/index.html
MOMOMIA/index.js
MOMOMIA/styles.css

Hello there,
I have added the veg/non-veg symbol on the cart modal, attaching an image for reference.
**> Image For Reference**
Thanks!

added veg/non-veg symbol to cart modal

---

MOMOMIA/index.html
MOMOMIA/index.js

Added the Active Navbar Menu Effect for Respective Sections on the  Webpage.
Accept this PR for hacktoberfest2022 !

button of navbar active for the respective Section

---

MOMOMIA/index.js
MOMOMIA/styles.css

Did CSS improvements for cart page

Improvements in Cart modal

---

MOMOMIA/index.html
MOMOMIA/index.js

Revert "added active status to navlinks on scroll to respective sections"

---

MOMOMIA/index.html
MOMOMIA/styles.css

Code for the website loader is included in index.html as well as styling is done in style.css. Also added the script text.

Added an aesthetic loader for the website.

---

MOMOMIA/index.html
MOMOMIA/terms_of_service.html

added index.html link to logo of both the pages.

added home page link to logo

---

MOMOMIA/styles.css

i have changed cart area color to white

changed cart area color

---

MOMOMIA/index.html
MOMOMIA/index.js
MOMOMIA/styles.css

Hey @RIKI-05 
I've fixed this following bugs 
1. Formatted the index file
2. 17 Inline css removed and added them to style.css
3. Two 'Go to Cart' button added
4. Formatted the total amount alignment
Before => 
After =>
If you want you can merge it and please label it as hacktoberfest also though my 4pr is completed but still label that too..

Many bugs fixed

---

MOMOMIA/contactus.html
MOMOMIA/index.html
MOMOMIA/policy.css
MOMOMIA/policy.html
MOMOMIA/terms_of_service.html

Successfully Solved issue: #186
Successfully added a policy page on the website which is missing before.
Please @RIKI-05  review and merge this PR under the Hactoberfest tag as I am the first to contribute in Open source.

Added a policy.html and policy.css so that Policy link works in the footer section

---

MOMOMIA/contactus.css

#192 
I have changed the color of the box that matches the background. I also have added border radius to the box and the input boxes too.

Improved the UI of Send Message box

---

MOMOMIA/contactus.css

Revert "Improved the UI of Send Message box"

---

MOMOMIA/contactus.css
MOMOMIA/contactus.html
MOMOMIA/styles.css

This is how it is looking. So can you please merge it , @RIKI-05

aligned menu at proper position

---

MOMOMIA/index.html
MOMOMIA/styles.css

Issue #207 
I've created a new section at the bottom which consists of testimonials provided by different users.

Added Testimonials Section

---

CONTRIBUTING.md

I've Created contributing.md file

---

MOMOMIA/index.html
MOMOMIA/index.js
MOMOMIA/styles.css

Hello @RIKI-05, I have made the mentioned changes in issue #216. Please let me know if anything is required.
Thanks.

Changed position of cart icon

---

MOMOMIA/index.js

Revert "Update index.js"

---

MOMOMIA/index.js

The amount is now properly displayed.
(FIXES : #237 )

Fixed issue #237

---

MOMOMIA/index.html

[FIXES : #241]
Cart icon takes to the cart pop up
https://www.loom.com/share/8f2e2ecc9fff4e19b8ca8570bdb51ad1

Fixed issue 241
